/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package read_files;

import javax.swing.JOptionPane;

/**
 *
 * @author desarrollador
 */
public class EditCode extends javax.swing.JFrame {

    Files_Manager fm = new Files_Manager("public/index.html");
    
    /**
     * Creates new form EditCode
     */
    public EditCode() {
        initComponents();
        
        //fm.write();
        
        
        fm.read_(edit_content);
        
        this.setTitle("Read Files");

        edit_content.setEditable(false);
        item_save.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        edit_content = new javax.swing.JEditorPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        item_open = new javax.swing.JMenuItem();
        item_edit = new javax.swing.JMenuItem();
        item_save = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        edit_content.setBackground(new java.awt.Color(254, 254, 254));
        edit_content.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        edit_content.setForeground(new java.awt.Color(44, 44, 44));
        edit_content.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edit_contentKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edit_contentKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(edit_content);

        jMenu1.setText("File");

        item_open.setText("Open");
        item_open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_openActionPerformed(evt);
            }
        });
        jMenu1.add(item_open);

        item_edit.setText("Edit");
        item_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_editActionPerformed(evt);
            }
        });
        jMenu1.add(item_edit);

        item_save.setText("Save");
        item_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_saveActionPerformed(evt);
            }
        });
        jMenu1.add(item_save);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edit_contentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edit_contentKeyPressed
        // TODO add your handling code here:
        
        
        if(edit_content.isEditable()){
            item_save.setEnabled(true);
            System.out.println(edit_content.getText());
        }
        
        
    }//GEN-LAST:event_edit_contentKeyPressed

    private void item_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_editActionPerformed
        // TODO add your handling code here:
        edit_content.setEditable(true);
        
    }//GEN-LAST:event_item_editActionPerformed

    private void item_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_saveActionPerformed
        // TODO add your handling code here:
        String text = edit_content.getText();
        
        System.out.println(text);
        
        fm.write(text);
        fm.read_(edit_content);
        
        item_save.setEnabled(false);
    }//GEN-LAST:event_item_saveActionPerformed

    private void edit_contentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edit_contentKeyTyped
        // TODO add your handling code here:
        char code =  evt.getKeyChar();
        System.out.println(evt.getExtendedKeyCode());
        if(edit_content.isEditable()){
            if(code == 's'){
                System.out.println(":)");
            }
        }
    }//GEN-LAST:event_edit_contentKeyTyped

    private void item_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_openActionPerformed
        // TODO add your handling code here:
        String name_file = JOptionPane.showInputDialog(this, "Write file pathname (Example: /home/user/script.txt)", "Open File", JOptionPane.QUESTION_MESSAGE);
        System.out.println(name_file);
        fm = new Files_Manager(name_file);
        
        fm.read_(edit_content);

        edit_content.setEditable(true);
        item_save.setEnabled(false);
    }//GEN-LAST:event_item_openActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane edit_content;
    private javax.swing.JMenuItem item_edit;
    private javax.swing.JMenuItem item_open;
    private javax.swing.JMenuItem item_save;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
